# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.

image: gcc:latest

pipelines:
  default:
    - parallel:
        - step:
            name: Build
            script:
              - apt update && apt install cmake -y
              # Execute your C++ application after compilation to check success
              - cmake -S . -B build
              - cmake --build build --target all
